[package]
name = "ring_test"
version = "0.1.0"
authors = ["Joseph Dunne <jd@lambda.tech>"]

[dependencies]
tokio-core = { git = "https://github.com/tokio-rs/tokio-core.git" }
futures = { git = "https://github.com/alexcrichton/futures-rs" }
